from app.dto import job, resume, candidate

def toJobDTO(payload: dict) -> job.JobAggregate:
    return job.JobAggregate(
        id=payload["id"],
        job_title=payload["job_title"],
        content=payload["content"],
        s_content=payload["s_content"],
        content_url=payload["content_url"],
        is_hiring=payload["is_hiring"],
        opened_date=payload["opened_date"],
        closed_date=payload["closed_date"],
        salary_from=payload["salary_from"],
        salary_to=payload["salary_to"],
        job_type=payload["job_type"],
        company_type=payload["company_type"],
        created_at=payload["created_at"],
        updated_at=payload["updated_at"],
        recruiter_id=payload["recruiter_id"],  
        recruiter_name=payload["recruiter_name"],
        job_tags=payload["job_tags"],
        address=payload["address"],
        city_name=payload["city_name"],
        country_name=payload["country_name"],
        hiring_level=payload["hiring_level"],
        applied_count=payload["applied_count"],
        address_id=payload["address_id"],
        work_place=payload["work_place"],
        display_content=payload["display_content"],
        common_job_title=payload["common_job_title"]
    )

def toJobWeaviateDTO(payload: dict) -> job.JobAggregate:
    return job.JobAggregate(
        id=payload.properties["job_id"],
        job_title=payload.properties["job_title"],
        content=payload.properties["content"],
        s_content=payload.properties["s_content"],
        content_url=payload.properties["content_url"],
        is_hiring=payload.properties["is_hiring"],
        opened_date=payload.properties["opened_date"],
        closed_date=payload.properties["closed_date"],
        salary_from=payload.properties["salary_from"],
        salary_to=payload.properties["salary_to"],
        job_type=payload.properties["job_type"],
        company_type=payload.properties["company_type"],
        created_at=payload.properties["created_at"],
        updated_at=payload.properties["updated_at"],
        recruiter_id=payload.properties["recruiter_id"],  
        recruiter_name=payload.properties["recruiter_name"],
        job_tags=payload.properties["job_tags"],
        address=payload.properties["address"],
        city_name=payload.properties["city_name"],
        country_name=payload.properties["country_name"],
        hiring_level=payload.properties["hiring_level"],
        applied_count=payload.properties["applied_count"],
        address_id=payload.properties["address_id"],
        work_place=payload.properties["work_place"],
        display_content=payload.properties["display_content"],
        common_job_title=payload.properties["common_job_title"]
    )

def toResumeDTO(payload: dict) -> resume.ResumeAggregate:
    return resume.ResumeAggregate (
        id=payload["id"],
        candidate_id=payload["candidate_id"],
        candidate_name=payload["candidate_name"],
        work_title=payload["work_title"],
        open_to_work=payload["open_to_work"],
        level=payload["level"],
        candidate_address=payload["candidate_address"],
        s_content=payload["s_content"],
        content=payload["content"],
        skills=payload["skills"],
        projects=payload["projects"],
        certificates=payload["certificates"],
        educations=payload["educations"],
        work_expericences=payload["work_expericences"],
        resume_link=payload["resume_link"],
        email=payload["email"],
        phone=payload["phone"],
        self_introduction=payload["self_introduction"],
        introduction=payload["introduction"]
    )

def toAppliedJobDTO(payload: dict, resume_id, resume_url) -> candidate.AppliedJobsResponse:
    return candidate.AppliedJobsResponse(
        id=payload["id"],
        job_title=payload["job_title"],
        content=payload["content"],
        s_content=payload["s_content"],
        content_url=payload["content_url"],
        is_hiring=payload["is_hiring"],
        opened_date=payload["opened_date"],
        closed_date=payload["closed_date"],
        salary_from=payload["salary_from"],
        salary_to=payload["salary_to"],
        job_type=payload["job_type"],
        company_type=payload["company_type"],
        created_at=payload["created_at"],
        updated_at=payload["updated_at"],
        recruiter_id=payload["recruiter_id"],  
        recruiter_name=payload["recruiter_name"],
        job_tags=payload["job_tags"],
        address=payload["address"],
        city_name=payload["city_name"],
        country_name=payload["country_name"],
        hiring_level=payload["hiring_level"],
        applied_count=payload["applied_count"],
        address_id=payload["address_id"],
        work_place=payload["work_place"],
        display_content=payload["display_content"],
        resume_id=resume_id,
        resume_url=resume_url
    )