import os

from dotenv import load_dotenv

import config.config as cfg

dotenv_path = os.path.join(cfg.ROOT_FOLDER, "builders", ".base.env")

load_dotenv(dotenv_path=dotenv_path)

# OpenAI API Key
OPENAI_API_KEY = str(os.getenv("OPENAI_KEY"))

# Models
OPENAI_EMBEDDING_MODEL = (str(os.getenv("OPENAI_EMBEDDING_MODEL")))
OPENAI_COMPLETION_MODEL_MINI = (str(os.getenv("OPENAI_COMPLETION_MODEL_MINI")))
OPENAI_COMPLETION_MODEL = (str(os.getenv("OPENAI_COMPLETION_MODEL")))
OPENAI_BEAST_COMPLETION_MODEL = (str(os.getenv("OPENAI_BEAST_COMPLETION_MODEL")))

# Prompts
SUMMARIZE_JOB_DESCRIPTION_PROMPT = (str(os.getenv("SUMMARIZE_JOB_DESCRIPTION_PROMPT")))
SUMMARIZE_RESUME_PROMPT = (str(os.getenv("SUMMARIZE_RESUME_PROMPT")))
COMMON_JOB_TITLE_PROMPT = (str(os.getenv("COMMON_JOB_TITLE_PROMPT")))
GET_SKILLS_AND_KNOWLEDGE_PROMPT = (str(os.getenv("GET_SKILLS_AND_KNOWLEDGE_PROMPT")))
GET_ACRONYMS_AND_ABBREVIATION_PROMPT = (str(os.getenv("GET_ACRONYMS_AND_ABBREVIATION_PROMPT")))
JOB_QUESTION_AND_ANSWERING_PROMPT = (str(os.getenv("JOB_QUESTION_AND_ANSWERING_PROMPT")))
RESUME_QUESTION_AND_ANSWERING_PROMPT = (str(os.getenv("RESUME_QUESTION_AND_ANSWERING_PROMPT")))


