WHITELIST_PATHS = [
    "/health-check", 
    "/docs",
    "/openapi.json",
    "/favicon.ico",
    "/api/jobs", 
    "/api/job", 
    "/api/related-jobs", 
    "/api/common/types",
    "/api/resume/enhance",
    "/api/admin/protected",
    "/api/admin/weaviate/create-job-class",
    "/api/admin/weaviate/create-jobqna-class",
    "/api/admin/weaviate/delete-class",
    "/api/admin/manual-sync-job",
] 