version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      start_period: 10s
      retries: 20
      interval: 10s
    volumes:
      - zookeeper-data:/usr/share/zookeeper/data
    networks:
      ccp_network:
        aliases:
          - zookeeper

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://157.245.50.16:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_JMX_PORT: 9101
      KAFKA_HOSTNAME: 157.245.50.16
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - broker-data:/usr/share/broker/data
    networks:
      ccp_network:
        aliases:
          - broker

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - broker
      - debezium
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: ccp_cdc
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
    networks:
      ccp_network:
        aliases:
          - kafka-ui

  debezium:
    image: debezium/connect:latest
    container_name: debezium
    hostname: debezium
    depends_on:
      - broker
      - ccp-db
    ports:
      - "8093:8083"
    environment:
      BOOTSTRAP_SERVERS: broker:29092
      CONNECT_REST_ADVERTISED_HOST_NAME: debezium
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      STATUS_STORAGE_TOPIC: connect_statuses
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      ENABLE_DEBEZIUM_SCRIPTING: "true"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "-X",
          "GET",
          "http://localhost:8083/connectors",
        ]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - debezium_connect-data:/usr/share/debezium_connect/data
    networks:
      ccp_network:
        aliases:
          - debezium

  connectors-ui:
    image: debezium/debezium-ui:latest
    container_name: connectors-ui
    hostname: connectors-ui
    depends_on:
      - debezium
    ports:
      - "8086:8080"
    environment:
      KAFKA_CONNECT_URIS: http://debezium:8083
    networks:
      ccp_network:

  ccp-db:
    image: postgres:16.1-alpine3.19
    container_name: ccp-db
    hostname: ccp-db
    restart: always
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      POSTGRES_DB: ccp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: change_me
    ports:
      - 5432:5432
    volumes:
      - posgresql-data:/usr/share/posgresql/data
    networks:
      ccp_network:
        aliases:
          - postgres
    healthcheck:
      test: pg_isready -U admin -d ccp -h localhost
      interval: 30s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - qdrant-data:/usr/share/qdrant/data
    networks:
      ccp_network:
        aliases:
          - qdrant

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/usr/share/minio/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: change_me
    command: server --console-address ":9001" /data
    networks:
      ccp_network:
        aliases:
          - minio

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=true
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - ELASTIC_PASSWORD=change_me
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      ccp_network:
        aliases:
          - elasticsearch

networks:
  ccp_network:
    name: ccp_network
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
  zookeeper-data:
    driver: local
  broker-data:
    driver: local
  debezium_connect-data:
    driver: local
  posgresql-data:
    driver: local
  qdrant-data:
    driver: local
  minio-data:
    driver: local
