version: "3.7"
services:
  ccp-pg:
    image: postgres:16.1-alpine3.19
    container_name: ccp-pg
    hostname: ccp-db
    restart: always
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      POSTGRES_DB: ccp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: change_me
    ports:
      - 5432:5432
    volumes:
      - posgresql-data:/usr/share/posgresql/data
    networks:
      ccp_network:
        aliases:
          - postgres
    healthcheck:
      test: pg_isready -U admin -d ccp -h localhost
      interval: 30s
      retries: 5

  ccp-qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: ccp-qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - qdrant-data:/usr/share/qdrant/data
    networks:
      ccp_network:
        aliases:
          - qdrant

  ccp-minio:
    image: minio/minio
    container_name: ccp-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/usr/share/minio/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: change_me
    command: server --console-address ":9001" /data
    networks:
      ccp_network:
        aliases:
          - minio

networks:
  ccp_network:
    name: ccp_network
    driver: bridge

volumes:
  posgresql-data:
    driver: local
  qdrant-data:
    driver: local
  minio-data:
    driver: local
