version: "3.7"
services:
  ccp-db:
    image: postgres:16.1-alpine3.19
    container_name: ccp-db
    restart: always
    environment:
      - POSTGRES_DB=ccp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=change_me
    ports:
      - 5432:5432
